[[redirects]]
  from = "/*"
  to = "/error404"
  status = 404 
[[redirects]]
  from = "/work.html"
  to = "/work"
  status = 200 
[[redirects]] 
  from = "/nishu"
  to = "/anshi/paper"
  status = 200
