[[redirects]] 
  from = "/nishu-paper"
  to = "/anshi/paper"
  status = 200
[[redirects]] 
  from = "/nishu-solution"
  to = "/anshi/solution"
  status = 200
[[redirects]]
  from = "/*"
  to = "/error404"
  status = 404 
[[redirects]]
  from = "/work.html"
  to = "/work"
  status = 200 

