const p1 = {
    "LANGHINDI": 55,
    "qu1": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Two infinitely long parallel wires are a distance d apart and carry equal parallel currents I in the same direction as shown in the figure. If the wires are located on y-axis (normal to x-y plane) at <img alt=\"y = \\frac{d}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141491041048460452.png\" \/>&nbsp;and <img alt=\"y = \u00a0- \\frac{d}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141491091083746127.png\" \/>, then the magnitude of x-coordinate of the point on x-axis where the magnitude of magnetic field is maximum is (Consider points on x-axis only)<\/div>\n<div style=\"text-align:center\"><img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149131187812880php5hNZbOimage.png\" style=\"height:175px; width:188px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"\\sqrt 2 d\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141491441684739936.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"\\frac{d}{{\\sqrt 2 }}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141491481310441694.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\">2d<\/div>",
            "OPT4": "<div style=\"text-align:justify\"><img alt=\"\\frac{d}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141491581449230408.png\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu2": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A projectile is fired vertically upward with an initial velocity u at t=0. After an interval of T seconds a second projectile is fired vertically upwards, also with initial velocity u.<\/div>",
            "OPT1": "<div style=\"text-align:justify\">They meet at time <img alt=\"t = \\frac{u}{g} - \\frac{T}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149220210719370.png\" \/>&nbsp; and at a height <img alt=\"\\frac{{{u^2}}}{{2g}} - \\frac{{g{T^2}}}{8}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141492261649078927.png\" \/>.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">They meet at time <img alt=\"t = \\frac{u}{g} + \\frac{T}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141492321482478710.png\" \/>&nbsp;and at a height <img alt=\"\\frac{{{u^2}}}{{2g}} + \\frac{{g{T^2}}}{8}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141492381432563130.png\" \/>.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">They meet at time <img alt=\"t = \\frac{u}{g} + \\frac{T}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149243459973554.png\" \/>&nbsp;and at a height <img alt=\"\\frac{{{u^2}}}{{2g}} - \\frac{{g{T^2}}}{8}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141492501345701678.png\" \/>.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">None of these.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu3": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">As shown in figure, a thin convex lens of focal length 20 cm is inclined at an angle of 53&deg; with x-axis. A point object is placed on the x-axis at a distance of 100 cm from the centre of the lens. Taking the origin as the centre of lens, find the x-coordinate of the image.<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141493191781682649phplCXQ3pimage.png\" style=\"height:115px; width:244px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\">26.7 cm<\/div>",
            "OPT2": "<div style=\"text-align:justify\">25 cm<\/div>",
            "OPT3": "<div style=\"text-align:justify\">33.3 cm<\/div>",
            "OPT4": "<div style=\"text-align:justify\">20 cm<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu4": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">In the following circuit the values of resistance in various arms are as shown. The galvanometer has a current sensitivity of &nbsp;<img alt=\"\\frac{{1mm}}{{100\\mu A}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141493771979083312.png\" \/>&nbsp;and an internal resistance of 1000 &Omega;. Calculate the deflection in galvanometer.<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141494021721160536phpX8Mxymimage.png\" style=\"height:129px; width:200px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\">Zero<\/div>",
            "OPT2": "<div style=\"text-align:justify\">10 mm<\/div>",
            "OPT3": "<div style=\"text-align:justify\">20 mm<\/div>",
            "OPT4": "<div style=\"text-align:justify\">30 mm<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu5": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">We released four wooden floating rafts on a river from port A. There is a boat whose speed relative to river is 4 m\/s irrespective of whether it is connected to a raft or not. At a time, only one raft can be connected to the boat. The rafts have to be carried to a port B at a distance of&nbsp;<span style=\"text-align:justify\">27 km downstream, the flow rate of the river is 2 m\/s. What is the approx. minimum time all &nbsp;rafts can be delivered to port B? Neglect the time to tie the raft to the boat and releasing it. Also neglect the dimensions of boat, raft and the connecting rope in comparison with 27km.<\/span><\/div>",
            "OPT1": "<div style=\"text-align:justify\">3 hrs. 45 min.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">2 hrs. 25 min.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">4 hrs. 35 min.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">1 hrs. 12 min.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu6": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Two blocks, of masses M and 2M, are placed next to each other on a horizontal smooth surface. The blocks are connected by a light spring with force constant k. Initially, the blocks are at rest. Then block M is given a quick push directly away from block 2M so that it acquires velocity v. The displacement of block M by the next moment its velocity equals v again is :<\/div>",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"2\\pi v\\sqrt {\\frac{{2m}}{{3k}}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141495001012920653.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"\\frac{{2\\pi v}}{3}\\sqrt {\\frac{{2m}}{{3k}}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141495041436487512.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\"><img alt=\"\\frac{{\\pi v}}{3}\\sqrt {\\frac{{2m}}{{3k}}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141495081453397571.png\" \/><\/div>",
            "OPT4": "<div style=\"text-align:justify\"><img alt=\"\\pi v\\sqrt {\\frac{{2m}}{{3k}}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149511821997173.png\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "196",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu7": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A stick of total length L is taken. A certain amount of charge is uniformly distributed along it&#39;s length. Let the resultant charge on the stick be Q and its mass be M. The entire structure is spun about the centre about an axis perpendicular to the stick with an angular velocity &omega;. There exists a uniform magnetic field B parallel to the axis of rotation. If the rotational kinetic energy is K, and energy of interaction of the structure with magnetic field is E,<\/div>",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"E = \u00a0- \\frac{{QBK}}{{M\\omega }}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141495802104781490.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"E = \u00a0- \\frac{{QBK}}{{2M\\omega }}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149584911339177.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\">To rotate the structure so that the angular velocity vector becomes perpendicular to the magnetic field, the external agent has to do positive work.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">To rotate the structure so that the angular velocity vector becomes perpendicular to the magnetic field, the external agent has to do negative work.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu8": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Two glass slabs of thickness t<sub>1<\/sub> and t<sub>2<\/sub> are joined to make L shape as shown in the figure. The refractive indices of both glass slabs are same. A light ray is incident at point &#39;P&#39; with an angle of incidence &#39;&theta;&#39; as shown in the figure. It is assumed that refraction takes place from both the glass slabs. Then choose the <strong>CORRECT <\/strong>option(s) :<\/div>\n\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614149701256288142phps8LnsUimage.png\" style=\"height:212px; width:198px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\">emergent ray passes from Q if t<sub>1<\/sub> = 2t<sub>2<\/sub>, &theta; = 30&deg;.&nbsp;<\/div>",
            "OPT2": "<div style=\"text-align:justify\">emergent ray passes from Q if t<sub>1<\/sub> = 2t<sub>2<\/sub>, &theta; = 45&deg;.&nbsp;<\/div>",
            "OPT3": "<div style=\"text-align:justify\">emergent ray passes above the &#39;Q&#39; if t<sub>2<\/sub> &gt; t<sub>1<\/sub>, &theta; = 45&deg;.&nbsp;<\/div>",
            "OPT4": "<div style=\"text-align:justify\">emergent ray passes below the &#39;Q&#39; if t<sub>2<\/sub> &lt; t<sub>1<\/sub>, &theta; = 45&deg;.&nbsp;<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu9": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A spherical concave mirror of radius of curvature 40 cm is moving with a constant velocity 2cm\/s along positive x-axis as shown. A point object &#39;P&#39; located at a distance 30 cm left to the pole of the concave mirror is also moving with a velocity of 4 cm\/s along positive x-axis at a height of 0.2 cm above the principal axis as shown in figure. Then choose the <strong>CORRECT<\/strong> option(s) :<\/div>\n\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150144180502811phpTA3wPsimage.png\" style=\"height:139px; width:345px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\">The velocity of image at this instant is 8 cm\/s along negative x-axis.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">The velocity of image at this instant is 6 cm\/s &nbsp;along negative x-axis.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">The velocity of image at this instant is zero along negative y-axis.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">The velocity of image at this instant is&nbsp;<img alt=\"\\frac{2}{{25}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150177260841375.png\" \/> cm\/s along negative y-axis.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu10": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A proton of charge &#39;e&#39; and mass &#39;m&#39; enters a uniform and constant magnetic field <img alt=\"\\vec B = B\\hat i\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141502111371919331.png\" \/>&nbsp;with an initial velocity <img alt=\"\\vec V = {V_{OX}}\\hat i + {V_{OY}}\\hat j\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141502201513551310.png\" \/>. Which of the following will be correct at any later time &#39;t&#39;:<\/div>",
            "OPT1": "<div style=\"text-align:justify\">x-component of velocity of the proton will be <img alt=\"{V_{OX}}\\cos \\left( {\\frac{{qBt}}{m}} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141502451605834724.png\" \/>.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">y-component of velocity will be <img alt=\"{V_{OY}}\\cos \\left( {\\frac{{qBt}}{m}} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141502501760536601.png\" \/>.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">z-component of velocity will be <img alt=\"{V_{OY}}\\sin \\left( {\\frac{{qBt}}{m}} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141502571433936437.png\" \/>&nbsp;along <img alt=\"\\left( { + \\hat k} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/161415027812383059.png\" \/>&nbsp;direction.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">x-component of velocity will remain unchanged.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu11": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A plane minor is placed in y-z plane facing towards negative x-axis. The mirror is moving in the positive y-direction with a speed of 2 cm\/s. A point object &#39;p&#39; is moving in front of the mirror with a velocity (1cm\/s)<img alt=\"\\hat i\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141503171348583064.png\" \/> + (1cm\/s)<img alt=\"\\hat j\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150326341307922.png\" \/>. Then which of the following statements is correct ?<\/div>",
            "OPT1": "<div style=\"text-align:justify\">The velocity of image is with <img alt=\"( - \\hat i + \\hat j)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141503531814719761.png\" \/>&nbsp;cm\/s.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">The velocity of image with respect to mirror is <img alt=\" - (\\hat i + \\hat j)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150358363223641.png\" \/>&nbsp;cm\/s.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">The velocity of image with respect to object is&nbsp;<img alt=\" - (2\\hat i)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141503641426390463.png\" \/> cm\/s.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">The unit vector in the direction of reflected ray is <img alt=\"\\frac{{(\\hat i + \\hat j)}}{{\\sqrt 2 }}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141503721743843236.png\" \/>.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu12": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A man weighing W stands on a horizontal beam (hinged on a wall) of negligible weight at point C and holds a massless rope passing over two smooth pulleys. The rope is attached to point B on the beam as shown. If the system is in equilibrium, then :-<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141504091332649385phpBrnqAximage.png\" style=\"height:133px; width:200px\" \/><\/div>",
            "OPT1": "<div style=\"text-align:justify\">If W = 600 N, tension in string is 400 N.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">If W = 600 N hinge force at A is 200 N.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">Hinge force at A is always in vertically downward direction, irrespective of value of W.<\/div>",
            "OPT4": "<div style=\"text-align:justify\">Hinge force at A is always in vertically upward direction, irrespective of value of W.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "197",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu13": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">The resistances in a burner of an electric table stove are connected together in an arrangement shown in figure. This arrangement is connected to the supply mains at points 1 and 2, and, after a certain time, 500 grams of water are heated to the boiling point. How much water (in gm) can be heated to the boiling point in the same time interval when the arrangement of resistances is connected to the supply mains at points 1 and 3? The initial temperature of the water is the same in both cases. Neglect all heat losses.<\/div>\n<div style=\"text-align:center\"><img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141506881901751929php225Pktimage.png\" style=\"height:168px; width:166px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu14": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Electrons are accelerated by an electron gun. As the electrons exit the gun they are deflected by a uniform magnetic field of fixed magnitude directed into the page. The electrons hit a small (point-like) target. An experimentalist noticed that if the magnetic field is directed along the line OT &nbsp;then also the electrons hit the target. For what minimum angle &alpha; is this possible? Fill the value of tan &alpha;. Assume that all electrons have the same initial velocity.<\/div>\n\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150893695719080phpNPVqw9image.png\" style=\"height:165px; width:267px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu15": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">In the circuit shown, When the switch S connects points A and D, the galvanometer deflects full-scale when the potential difference between X and Y is 100 V. When the switch S connects points B and D, the galvanometer deflects full-scale when the potential difference between X and Y is 1000 V. What value of R (in &Omega;) is needed to cause the galvanometer to deflect full-scale when the potential difference between X and Y is 10 kV when the switch S connects C to D ? Fill value of <img alt=\"\\frac{R}{{10}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614150952589624468.png\" \/>.<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141509712007525463phpcDcQHkimage.png\" style=\"height:113px; width:472px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu16": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A uniform solid right prism whose cross section is an isosceles right triangle with height h and width w = 2h is placed on an incline that has a variable angle with the horizontal &theta;. What is the minimum coefficient of static friction so that the prism topples before it begins sliding as &theta; is slowly increased from zero ?<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614151077576364295php17bVWKimage.png\" style=\"height:151px; width:227px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu17": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A car drives anticlockwise (counterclockwise) around a flat, circular curve at constant speed, so that the left, front wheel traces out a circular path of radius R = 9.60 m. If the width of the car is 1.74 m, what is the ratio of the angular velocity about its axle of the left, front wheel to that of the right, front wheel, of the car as it moves through the curve? Assume the wheels roll without slipping.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu18": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">A bright source S is kept on the principal axis of a concave mirror of focal length f = 20 cm at a distance d = 30 cm from its pole. Find the distance D (in cm) in front of the concave mirror where a plane mirror should be placed so that the ray after being reflected first at the concave mirror and then by the plane mirror return to the point S.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "1",
        "TOPIC_ID": "198",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "PHYSICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu19": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Which of following curve represent equilibrium of vapour with its pure liquid at constant temperature, if equilibrium is achieved by taking vapour of pure liquid initially -&nbsp;<\/div>",
            "OPT1": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16142429461539735226phpypXqE9image.png\" style=\"height:190px; width:200px\">",
            "OPT2": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614151409524999957phpjb0xwTimage.png\" style=\"height:213px; width:230px\">",
            "OPT3": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141514191974399791phpD9QBotimage.png\" style=\"height:205px; width:220px\">",
            "OPT4": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141514321481554357phpnuXZ0Zimage.png\" style=\"height:209px; width:220px\">",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu20": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Copper is extracted from copper pyrites ore by heating in blast furnace the method is based on the principle that :-<\/div>",
            "OPT1": "<div style=\"text-align:justify\">Copper has more affinity for oxygen than sulphur at higt temperature<\/div>",
            "OPT2": "<div style=\"text-align:justify\">Iron has less affinity for oxygen than sulphur at high temperature<\/div>",
            "OPT3": "<div style=\"text-align:justify\">Sulphur has less affinity for oxygen at high temperature<\/div>",
            "OPT4": "<div style=\"text-align:justify\">Copper has less affinity for oxygen than sulphur at high temperature<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu21": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Identify pair in which I<sup>st<\/sup> structure is more stable than II<sup>nd<\/sup> ?<\/div>",
            "OPT1": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141515271053370481phpq4guxQimage.png\" style=\"height:100px; width:220px\">",
            "OPT2": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614151540147852854phpWymH5mimage.png\" style=\"height:82px; width:180px\">",
            "OPT3": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141515541311005082phpV7wdtHimage.png\" style=\"height:74px; width:200px\">",
            "OPT4": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141515662053829097phpokrsnoimage.png\" style=\"height:72px; width:200px\">",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu22": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">2.08 kg of an equimolar mixture of ferrous oxalate (MW = 144) and ferric oxalate&nbsp;(MW = 376) require X moles of K<sub>2<\/sub>Cr<sub>2<\/sub>O<sub>7<\/sub> in acidic medium for complete oxidation. Then &#39;X&#39; is - &nbsp;<\/div>",
            "OPT1": "16\/3",
            "OPT2": "6",
            "OPT3": "32\/3",
            "OPT4": "10\/3",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu23": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Select <strong>CORRECT <\/strong>for reaction ?<\/div>\n<div style=\"text-align:center\">Na<sub>2<\/sub>CrO<sub>4<\/sub> + H<sub>2<\/sub>SO<sub>4<\/sub> &mdash;&rarr;<\/div>",
            "OPT1": "<div style=\"text-align:justify\">It is a redox reaction in which green solution of [Cr(H<sub>2<\/sub>O)<sub>6<\/sub>]<sup>+3<\/sup> is produce<\/div>",
            "OPT2": "<div style=\"text-align:justify\">One of the product in reaction has trigonal planar structure<\/div>",
            "OPT3": "<div style=\"text-align:justify\">Orange solution of <img alt=\"C{r_2}O_7^{2 - }\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614156543619848460.png\" \/>&nbsp;is produce<\/div>",
            "OPT4": "<div style=\"text-align:justify\">Dark blue colour is obtain in reaction<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu24": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Identify correct order of heat of combution ?<\/div>",
            "OPT1": "Me&ndash;C&equiv;CH &lt; CH<sub>2<\/sub>=C=CH<sub>2<\/sub>",
            "OPT2": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614156633879405418phpkK8XU3image.png\" style=\"height:41px; width:135px\" \/>",
            "OPT3": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141566451328930783php8X3SD5image.png\" style=\"height:48px; width:163px\" \/>",
            "OPT4": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/161415665690067183phpgh7VXSimage.png\" style=\"height:83px; width:170px\" \/>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "199",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu25": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Pure benzene has a vapour pressure 900 torr and pure toluene has a vapour pressure&nbsp;<span style=\"text-align:justify\">360 torr. If a solution is prepared by mixing 39gm benzene and 46 gm toluene then&nbsp;&nbsp;<\/span><\/div>",
            "OPT1": "<div style=\"text-align:justify\">Vapour pressure of its distillate will be be 745.714 torr<\/div>",
            "OPT2": "<div style=\"text-align:justify\">Vapour pressure of initial solution will be 630 torr<\/div>",
            "OPT3": "<div style=\"text-align:justify\">Mole % of benzene in vapour phase of solution will be&nbsp;<img alt=\"\\frac{{500}}{7}\\% \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141573071369719428.png\" \/> &nbsp;<\/div>",
            "OPT4": "<div style=\"text-align:justify\">Mole % of toluene in its distillate will be 50%.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu26": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Which of the following is\/are <strong>CORRECTLY <\/strong>matched?<\/div>",
            "OPT1": "<div style=\"text-align:justify\">[Co(H<sub>2<\/sub>O)<sub>6<\/sub>]SO<sub>4<\/sub> : Paramagnetic, high spin complex<\/div>",
            "OPT2": "<div style=\"text-align:justify\">[Fe(H<sub>2<\/sub>O)<sub>5<\/sub>NO]SO<sub>4<\/sub> : coloured, low spin complex<\/div>",
            "OPT3": "<div style=\"text-align:justify\">[Cu(NH<sub>3<\/sub>)<sub>4<\/sub>]SO<sub>4<\/sub> : square planar, coloured<\/div>",
            "OPT4": "<div style=\"text-align:justify\">[NiF<sub>6<\/sub>]<sup>&ndash;2<\/sup> : diamagnetic, &Delta;<sub>O<\/sub> &gt; pairing energy<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu27": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">How many of following compounds contain odd number of &#39;D&#39; atom in its enol form after prolong treatment with <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141574871539731773phpOToPhpimage.png\" style=\"height:16px; width:36px\" \/>&nbsp;\/ D<sub>2<\/sub>O :<\/div>",
            "OPT1": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614157532192544517phpM1KaMYimage.png\" style=\"height:65px; width:89px\" \/>",
            "OPT2": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141575421667746986phplS0Jypimage.png\" style=\"height:105px; width:68px\" \/>",
            "OPT3": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141575541684908425php4EKtkvimage.png\" style=\"height:60px; width:89px\" \/>",
            "OPT4": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614157566982523841phpY4JL3mimage.png\" style=\"height:64px; width:89px\" \/>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu28": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">An atom of U<sup>238<\/sup> disintegrates by a series of &alpha;-decays and &beta;-decays until it becomes Pb<sup>206<\/sup> which is stable. How many of the following ten nuclides may formed from the series of distintegration starting at U<sup>238<\/sup>.<\/div>\n\n<div style=\"text-align:center\">U<sup>235<\/sup>, U<sup>234<\/sup>, Ac<sup>228<\/sup>, Ra<sup>224<\/sup>, Rn<sup>224<\/sup>, Rn<sup>220<\/sup>, Po<sup>215<\/sup>, Po<sup>212<\/sup>, Pb<sup>212<\/sup>, Pb<sup>211<\/sup><\/div>",
            "OPT1": "1",
            "OPT2": "6",
            "OPT3": "7",
            "OPT4": "4",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu29": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Which of the following statement is\/are <strong>CORRECT<\/strong> ?<\/div>",
            "OPT1": "<div style=\"text-align:justify\">[Pd<sup>+2<\/sup>(NH<sub>2<\/sub>&ndash;CH(CH<sub>3<\/sub>)&ndash;<img alt=\"CO_2^ - \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614157748833029279.png\" \/>)<sub>2<\/sub>]<sup>0<\/sup> and [Zn(gly)<sub>2<\/sub>] complex does not show geometrical isomerism but show optical isomerism.<\/div>",
            "OPT2": "<div style=\"text-align:justify\">In [PtCl<sub>2<\/sub>(NCS)<sub>2<\/sub>]<sup>&ndash;2<\/sup> geometrical isomerism exist, while optical isomerism does not exist<\/div>",
            "OPT3": "<div style=\"text-align:justify\">Na<sub>2<\/sub>[Pt(SCN)<sub>2<\/sub>(ox)<sub>2<\/sub>] complex show structural and stereo isomerism<\/div>",
            "OPT4": "<div style=\"text-align:justify\">[NiCl<sub>2<\/sub>(PPh<sub>3<\/sub>)<sub>2<\/sub>] (<img alt=\"\\mu \u00a0= \\sqrt 8 \\,\\,B.M.\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141578281413849713.png\" \/>) complex show geometrical isomerism<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu30": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">In which of the following pair of compounds, order of pK<sub>a<\/sub> is correct :<\/div>",
            "OPT1": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614157876287060156phpUjiuXbimage.png\" style=\"height:102px; width:250px\">",
            "OPT2": "<img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614157889405544706phpKNevurimage.png\" style=\"height:118px; width:200px\">",
            "OPT3": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141579011703949647php2djjRVimage.png\" style=\"height:125px; width:230px\">",
            "OPT4": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141579141822387412phpJT4yQtimage.png\" style=\"height:115px; width:240px\">",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "200",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu31": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">In ZnS (density = 4 gm\/ml) unit cell all following manipulations are done -&nbsp;<br \/>\n(i) All ions along one body diagonal are removed&nbsp;<br \/>\n(ii) After step (i) one Zn<sup>2+<\/sup> is swapped by face centered s<sup>&ndash;2<\/sup> ion.<br \/>\nFind density of final unit cell if volume of unit cell remain unchanged [Zn = 65.4, S = 32].<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu32": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Find the total number of molecules\/ions in which total number of antibonding electrons are more than the total number of bonding electrons?<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141585091362263280php5cGaLzimage.png\" style=\"height:32px; width:375px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu33": {
        "ENGLISH": {
            "QUESTION_TEXT": "Find the number of compound which can show geometrical isomerism -\n<div style=\"text-align:center\"><img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614158743628660222phpKgz030image.png\" style=\"height:237px; width:620px\" \/><\/div>\n&nbsp;&nbsp; &nbsp;",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu34": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">In any polytropic process, molar heat capacity of ideal gas is &#39;Cp &ndash; 2R&#39; , calculate work done (in kcal) if one mole of ideal gas is compressed from 300K, 2L to 0.5 litre. [R = 2cal\/K-mole]<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu35": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Consider the following statements.<br \/>\n(i) Total number of oxygen atoms participate in ring formation in [Co(EDTA)]<sup>&ndash;1<\/sup> = &#39;X&#39;<br \/>\n(ii) Total number of five membered rings are in [Co(dien)(NH<sub>3<\/sub>)<sub>3<\/sub>]<sup>+3<\/sup> = Y<br \/>\n(iii) Maximum number of denticity shown by dmg<sup>&ndash;1<\/sup> in [Ni(DMG)<sub>2<\/sub>] = Z<br \/>\nthen find the value of &nbsp;<img alt=\"\\frac{{X + Y}}{Z}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141588801352296609.png\" \/>&nbsp;= ?<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu36": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Degree of unsaturation of following compound is :<\/div>\n<div style=\"text-align:center\"><img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141589251289091809phpjfmTiqimage.png\" style=\"height:103px; width:120px\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "8",
        "TOPIC_ID": "201",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "CHEMISTRY",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu37": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">If tan<sup>&ndash;1<\/sup>(x + 1) + cot<sup>&ndash;1<\/sup>(x&ndash;1) = <img alt=\"{\\sin ^{ - 1}}\\frac{4}{5} + {\\cos ^{ - 1}}\\frac{3}{5}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138551749043968.png\" \/>, then possible value of x is<\/div>",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"4\\sqrt {\\frac{3}{7}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138558956175881.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"4\\sqrt {\\frac{7}{3}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138565647668728.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\"><img alt=\" - 4\\sqrt {\\frac{7}{3}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141385701257650504.png\" \/><\/div>",
            "OPT4": "<div style=\"text-align:justify\"><img alt=\"6\\sqrt 7 \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138576820300073.png\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu38": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Given that &fnof;(x) is a function defined on <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\" \/>, satisfying &fnof;(1) = 1 and for any x &isin; <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\" \/>,&nbsp;&fnof;(x + 5) <u>&gt;<\/u> &fnof;(x) + 5 and &fnof;(x + 1) <u>&lt;<\/u> &fnof;(x) + 1. If g(x) = &fnof;(x) + 5 &ndash; x, then g(2021) is equal to-<\/div>",
            "OPT1": "<div style=\"text-align:justify\">3<\/div>",
            "OPT2": "<div style=\"text-align:justify\">4<\/div>",
            "OPT3": "<div style=\"text-align:justify\">5<\/div>",
            "OPT4": "<div style=\"text-align:justify\">6<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu39": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">If [x]<sup>3<\/sup> + [y]<sup>3<\/sup> + [z]<sup>3<\/sup> &ndash; 3[x] [y] [z] = 4 where x,y,z &gt; 0 then minimum possible value of (x + y + z) is &nbsp;(where [.] denotes greatest integer function)<\/div>",
            "OPT1": "<div style=\"text-align:justify\">1<\/div>",
            "OPT2": "<div style=\"text-align:justify\">2<\/div>",
            "OPT3": "<div style=\"text-align:justify\">3<\/div>",
            "OPT4": "<div style=\"text-align:justify\">4<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu40": {
        "ENGLISH": {
            "QUESTION_TEXT": "Let <img alt=\"{\\left( {1 + \\sqrt 2 } \\right)^n} = {A_n} + {B_n}\\sqrt 2 \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141387411060739282.png\" \/>, where A<sub>n<\/sub> and B<sub>n<\/sub> are rational numbers and n &isin; <img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614165877102074023phpwc484Vimage.png\" style=\"height:17px; width:15px\" \/>, then the value of <img alt=\"\\mathop {\\lim }\\limits_{n \\to \\infty } \\frac{{{A_n}}}{{{B_n}}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141387491765857015.png\" \/>&nbsp;is equal to -<br \/>\n(where [.] denotes greatest integer function)",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"\\left[ {\\mathop {\\lim }\\limits_{x \\to 0} \\frac{{\\sin x}}{x}} \\right]\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138756308630603.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"\\mathop {\\lim }\\limits_{x \\to 0} \\left[ {\\frac{{\\sin x}}{x}} \\right]\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141387632079628486.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\"><img alt=\"\\mathop {\\lim }\\limits_{x \\to \\frac{\\pi }{4}} \\frac{{|\\cos x - \\sin x|}}{{\\left| {x - \\frac{\\pi }{4}} \\right|}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141387751336770799.png\" \/><\/div>",
            "OPT4": "<div style=\"text-align:justify\"><img alt=\"\\left[ {\\mathop {\\lim }\\limits_{x \\to 0} \\frac{{\\sin \\sqrt 2 \\,x}}{x}} \\right]\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138781891910769.png\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu41": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">If n &isin; <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614141065983859995phpDMM0zcimage.png\" style=\"height:20px; width:18px\" \/>&nbsp;and&nbsp; &fnof;(x) =&nbsp;<img alt=\"\\left( {^n{C_0}x + 1} \\right)\\left( {^n{C_1}x + 2} \\right)\\left( {^n{C_2}x + 3} \\right)\\left( {^n{C_3}x + 4} \\right)....\\left( {^n{C_n}x + n + 1} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614141098682905964.png\" \/>&nbsp;and &fnof;&#39;(0) = <img alt=\"\\frac{3}{2}\\left( {7!} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614141116378727582.png\" \/>, then n is equal to<\/div>",
            "OPT1": "<div style=\"text-align:justify\">3<\/div>",
            "OPT2": "<div style=\"text-align:justify\">4<\/div>",
            "OPT3": "<div style=\"text-align:justify\">5<\/div>",
            "OPT4": "<div style=\"text-align:justify\">6<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu42": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Let the function p, q and r defined by p(x) = x<sup>\u2113nx<\/sup>, q(x) = (\u2113nx)<sup>x<\/sup>,<img alt=\"r(x) = {\\log _{{e^x}}}x\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141389471794956015.png\" \/> , then the value of <img alt=\"\\frac{{p'({e^{ - 1}}).r'({e^2})}}{{q'(e)}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141389561478058293.png\" \/>&nbsp;is &nbsp;(where y&#39; denotes the derivative of y)<\/div>",
            "OPT1": "<div style=\"text-align:justify\"><img alt=\"\\frac{1}{e}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141389691633058933.png\" \/><\/div>",
            "OPT2": "<div style=\"text-align:justify\"><img alt=\"\\frac{1}{{{e^2}}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138974495512698.png\" \/><\/div>",
            "OPT3": "<div style=\"text-align:justify\"><img alt=\"\\frac{2}{e}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141389801872636374.png\" \/><\/div>",
            "OPT4": "<div style=\"text-align:justify\"><img alt=\"\\frac{2}{{{e^2}}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614138986414075814.png\" \/><\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "202",
        "QUESTION_TYPE": "7",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-1",
        "RIGHT_MARKS": "3.00",
        "WRONG_MARKS": "1.00",
        "TIME": ""
    },
    "qu43": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Identify the <strong>CORRECT<\/strong> statements-<\/div>",
            "OPT1": "<div style=\"text-align:justify\">Sum of two periodic functions may or maynot be a periodic function<\/div>",
            "OPT2": "<div style=\"text-align:justify\">A differentiable function in <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\"> will always be continuous in <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\">.<\/div>",
            "OPT3": "<div style=\"text-align:justify\">A continuous function whose domain is in a closed interval is always bounded<\/div>",
            "OPT4": "<div style=\"text-align:justify\">In [a,b] for a function \u0192(x), if \u0192(a). \u0192(b) &lt; 0, then there exists atleast one root of \u0192(x) = 0 in (a,b).<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu44": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">If <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141413431065899551phpzZe1msimage.png\" style=\"height:45px; width:174px\" \/>, then which of the following statement(s) holds good ?<\/div>",
            "OPT1": "<div style=\"text-align:justify\">\u0192(x) is continuous at x = 1<\/div>",
            "OPT2": "<div style=\"text-align:justify\">\u0192(x) is discontinuous at x = 1<\/div>",
            "OPT3": "<div style=\"text-align:justify\"><img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141414071773826383phpdYMrVhimage.png\" style=\"height:26px; width:60px\">&nbsp;exists finitely<\/div>",
            "OPT4": "<img class=\"\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/161414143389959993phpaz1UgPimage.png\" style=\"height:25px; width:60px\">&nbsp;does not exist",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu45": {
        "ENGLISH": {
            "QUESTION_TEXT": "If &fnof;<img alt=\"\\left( x \\right) = \\left\\{ {\\begin{array}{*{20}{c}} {{{\\cos }^{ - 1}}\\left( {\\cos x} \\right);}&amp;{|x| &lt; \\pi }\\\\[0.9em] {\\pi {{\\log }_\\pi }|x|;}&amp;{|x| \\geqslant \\pi } \\end{array}} \\right.\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614139288540014117.png\" \/>, then correct statement(s) is\/are -",
            "OPT1": "<div style=\"text-align:justify\">\u0192(x) is not differentiable at three points.<\/div>",
            "OPT2": "\u0192'(\u03c0<sup>+<\/sup>) + \u0192'(\u2013\u03c0<sup>\u2013<\/sup>) = 0&nbsp;&nbsp; &nbsp;",
            "OPT3": "\u0192'(\u03c0<sup>+<\/sup>) = \u0192'(\u2013\u03c0<sup>\u2013<\/sup>)",
            "OPT4": "\u0192'(0<sup>+<\/sup>) + \u0192'(0<sup>\u2013<\/sup>) = 0",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu46": {
        "ENGLISH": {
            "QUESTION_TEXT": "The function &fnof;(x) = (cosx) [cosx] in (0,2&pi;)- (where [.] denotes GIF)",
            "OPT1": "<div style=\"text-align:justify\">is discontinuous at two points<\/div>",
            "OPT2": "<div style=\"text-align:justify\">is non differentiable at two points<\/div>",
            "OPT3": "<div style=\"text-align:justify\">has range (0,1]<\/div>",
            "OPT4": "<div style=\"text-align:justify\">is such that &fnof;(&fnof;(x)) + 1 = 0 has no real roots.<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu47": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Given<img alt=\"\\mathop {\\lim }\\limits_{x \\to \\alpha } \\frac{{\\sin \\left( {\\left[ {{x^3}} \\right] - {{\\left[ x \\right]}^3}} \\right)}}{{{{\\left( {x - \\alpha } \\right)}^3}}}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141393661583435942.png\" \/> exists finitely, then the value of &alpha; can be (where &alpha; &isin; I &amp; [.] denotes greatest integer function)-<\/div>",
            "OPT1": "<div style=\"text-align:justify\">0<\/div>",
            "OPT2": "<div style=\"text-align:justify\">1<\/div>",
            "OPT3": "<div style=\"text-align:justify\">&ndash;1<\/div>",
            "OPT4": "<div style=\"text-align:justify\">2<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu48": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Let &fnof;<img alt=\"(x) = \\left\\{ {\\begin{array}{*{20}{c}} {\\min \\left\\{ {{{\\sin }^{ - 1}}x,{{\\cos }^{ - 1}}x} \\right\\}}&amp;;&amp;{0 \\leqslant x \\leqslant 1}\\\\[0.9em] {\\max .\\left\\{ {{{\\sin }^{ - 1}}x,{{\\cos }^{ - 1}}x} \\right\\}}&amp;;&amp;{ - 1 \\leqslant x &lt; 0} \\end{array}} \\right.\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141394281304632569.png\" \/> and&nbsp;<img alt=\"f(x) = \\frac{1}{2}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141394392144626584.png\" \/> , <img alt=\"f(x) = \\frac{1}{4}\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141394541990664930.png\" \/>&nbsp;&amp; &fnof;(x) = 2 has number of solution(s) &lambda;<sub>1<\/sub>,&lambda;<sub>2<\/sub>,&lambda;<sub>3<\/sub> respectively, then<\/div>",
            "OPT1": "<div style=\"text-align:justify\">&lambda;<sub>1<\/sub> = 2<\/div>",
            "OPT2": "<div style=\"text-align:justify\">&lambda;<sub>2<\/sub> = 1<\/div>",
            "OPT3": "<div style=\"text-align:justify\">&lambda;<sub>2<\/sub> = 2<\/div>",
            "OPT4": "<div style=\"text-align:justify\">&lambda;<sub>3<\/sub> = 1<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "203",
        "QUESTION_TYPE": "5",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-2",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "2.00",
        "TIME": ""
    },
    "qu49": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Let A = {1, 2, 3, 4}, B = {1, 2, 3, 4}. The total number of functions &fnof; : A &rarr; B such that&nbsp;&fnof;(x) &ne; x &forall; x &isin; A and range of &fnof;(x) contains exactly three elements, is&nbsp;<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu50": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">The number of values of x, x &isin; [&ndash;2,3] where &fnof;(x) = [x<sup>2<\/sup>] sin(&pi;x) is discontinuous, is&nbsp;<br \/>\n(where [.] denotes greatest integer function)-<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu51": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Number of points where &fnof;(x) = |(2<sup>x<\/sup> &ndash; 1).(3<sup>x<\/sup> &ndash; 3)x.(x &ndash; 1).(x &ndash; 2)| is not differentiable<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu52": {
        "ENGLISH": {
            "QUESTION_TEXT": "<div style=\"text-align:justify\">Let <img alt=\"{S_n} = \\sum\\limits_{k = 0}^n {{{\\tan }^{ - 1}}\\frac{{49}}{{49{k^2} + 63k + 57}}} \" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614139641140295577.png\" \/>&nbsp;then <img alt=\"\\cot \\left( {\\mathop {\\lim }\\limits_{n \\to \\infty } {S_n}} \\right)\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141396511271095661.png\" \/>&nbsp;is equal to<\/div>",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu53": {
        "ENGLISH": {
            "QUESTION_TEXT": "Let &fnof;(x) be a twice differentiable function satisfying x&fnof;(x<sup>2<\/sup>) + (x<sup>2<\/sup> + 1)&fnof;(x) = x, &forall; x &isin; <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\" \/> then the value of |&fnof;&quot;(1)| is",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    },
    "qu54": {
        "ENGLISH": {
            "QUESTION_TEXT": "Let &fnof;<img alt=\"(x) = \\left\\{ {\\begin{array}{*{20}{c}} {ax}&amp;;&amp;{x &lt; 2}\\\\[0.9em] {a{x^2} - bx + 3}&amp;;&amp;{x \\geqslant 2} \\end{array}} \\right.\" src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/1614139783923167801.png\" \/>&nbsp;and &#39;&fnof;&#39; is differentiable &forall; x&isin; <img src=\"https:\/\/d2lbh14zkcqlst.cloudfront.net\/content_data\/content_images\/16141658151354713477phpSJO09Himage.png\" style=\"height:17px; width:15px\" \/>, then (a + b) is equal to -",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "HINDI": {
            "QUESTION_TEXT": "",
            "CORRECT_ANSWER": " ",
            "SOLUTION": "",
            "ESSAY_ID": "0",
            "EASSY_DETAILS": " ",
            "ESSAY_NAME": "ESSAY_NAME"
        },
        "SUBJECT_ID": "9",
        "TOPIC_ID": "204",
        "QUESTION_TYPE": "2",
        "IS_IMAGE_TYPE": "0",
        "IS_COMPILER": "0",
        "SUBJECT_NAME": "MATHEMATICS",
        "TOPIC_NAME": "SEC-3",
        "RIGHT_MARKS": "4.00",
        "WRONG_MARKS": "0.00",
        "TIME": ""
    }
}